# Generated by Django 3.1.4 on 2021-03-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, verbose_name='Soyadınız ')),
                ('adreess', models.CharField(max_length=200, verbose_name='Adres Bilgisi ')),
                ('city', models.CharField(choices=[('İstanbul', 'İstanbul'), ('izmir', 'izmir'), ('Ankara', 'Ankara'), ('Bursa', 'Bursa'), ('Çanakkale', 'Çanakkale')], max_length=200, verbose_name='İl')),
                ('state', models.CharField(max_length=200, verbose_name='İlçe')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Mahalle')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('address_title', models.CharField(max_length=200, verbose_name='Adres Başlıgı ')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.order')),
            ],
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
