# Generated by Django 3.1.4 on 2021-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20210322_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddres',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Adınız '),
        ),
    ]
