# Generated by Django 3.1.4 on 2021-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20210323_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddres',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon numarası '),
        ),
    ]
