# Generated by Django 3.1.4 on 2021-03-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20210323_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
