# Generated by Django 3.1.4 on 2021-03-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_remove_shippingaddres_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddres',
            old_name='adreess',
            new_name='address',
        ),
    ]
