# Generated by Django 3.1.4 on 2021-03-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20210325_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddres',
            name='address_title',
        ),
    ]
