# Generated by Django 3.1.4 on 2021-05-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20210325_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-transaction_id']},
        ),
    ]
