# Generated by Django 3.1.4 on 2021-05-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0072_auto_20210506_0016'),
        ('Store', '0012_auto_20210506_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='chooseColor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seçilenRenk', to='Main.color'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='chooseSize',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seçilenSize', to='Main.size'),
        ),
    ]
