# Generated by Django 3.1.4 on 2021-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_auto_20210506_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='chooseColor',
            field=models.CharField(max_length=20, null=True, verbose_name='Seçilen Renk'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='chooseSize',
            field=models.CharField(max_length=25, null=True, verbose_name='Seçilen Boyut'),
        ),
    ]
