# Generated by Django 3.1.4 on 2021-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_auto_20210507_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.CharField(max_length=100, verbose_name='Sipariş alınma tarıhı'),
        ),
    ]
