# Generated by Django 3.1.4 on 2021-05-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_auto_20210507_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='dateOrdered',
        ),
    ]
