# Generated by Django 3.1.4 on 2021-05-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0084_auto_20210508_1750'),
        ('Store', '0018_auto_20210507_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product'),
        ),
    ]
