# Generated by Django 3.1.4 on 2021-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_auto_20210508_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderStatus',
            field=models.BooleanField(default=False, null=True, verbose_name='ürün satıldıysa evet satılmadıysa hayır durumundadır '),
        ),
    ]
