# Generated by Django 3.1.4 on 2021-05-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_orderitem_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddres',
            name='order',
        ),
        migrations.AddField(
            model_name='shippingaddres',
            name='address_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Adres Başlıgı '),
        ),
        migrations.AddField(
            model_name='shippingaddres',
            name='surname',
            field=models.CharField(max_length=200, null=True, verbose_name='Soyadınız '),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Şehir'),
        ),
    ]
