# Generated by Django 3.1.4 on 2021-05-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_auto_20210515_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddres',
            old_name='address_title',
            new_name='title',
        ),
    ]
