# Generated by Django 3.1.4 on 2021-05-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_auto_20210515_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddres',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon '),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='surname',
            field=models.CharField(max_length=200, null=True, verbose_name=''),
        ),
    ]
