# Generated by Django 3.1.4 on 2021-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_auto_20210517_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddres',
            name='order',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
    ]
