# Generated by Django 3.1.4 on 2021-05-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_shippingaddres_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddres',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.order'),
        ),
    ]
