# Generated by Django 3.1.4 on 2021-04-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210403_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size2',
        ),
    ]
