# Generated by Django 3.1.4 on 2021-04-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_size2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
