# Generated by Django 3.1.4 on 2021-04-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210403_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
    ]
