# Generated by Django 3.1.4 on 2021-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Email '),
        ),
    ]
