# Generated by Django 3.1.4 on 2021-02-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
