# Generated by Django 3.1.4 on 2021-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20210227_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.CharField(default='..  TL ', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='..   TL', max_length=12),
        ),
    ]
