# Generated by Django 3.1.4 on 2021-02-28 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0010_auto_20210227_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21, verbose_name='Ad *')),
                ('email', models.EmailField(help_text='Email gerekli', max_length=254, verbose_name='Email *')),
                ('message', models.TextField(verbose_name='Messajınız *')),
                ('kullanıcı', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı adı * ')),
            ],
        ),
    ]
