# Generated by Django 3.1.4 on 2021-03-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_auto_20210302_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
