# Generated by Django 3.1.4 on 2021-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20210303_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='heart',
            field=models.IntegerField(default=0),
        ),
    ]
