# Generated by Django 3.1.4 on 2021-03-06 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0026_product_heart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='heart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Begenenler'),
        ),
    ]
