# Generated by Django 3.1.4 on 2021-03-06 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0029_auto_20210306_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Related_comment_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
