# Generated by Django 3.1.4 on 2021-03-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20210306_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='heart',
            new_name='size2',
        ),
    ]
