# Generated by Django 3.1.4 on 2021-03-06 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0035_auto_20210306_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='heart',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
