# Generated by Django 3.1.4 on 2021-03-06 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0036_auto_20210306_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='heart',
        ),
        migrations.AddField(
            model_name='product',
            name='heart',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
