# Generated by Django 3.1.4 on 2021-03-06 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0037_auto_20210306_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='heart',
            field=models.ManyToManyField(blank=True, null=True, related_name='P_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
