# Generated by Django 3.1.4 on 2021-03-07 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0038_auto_20210307_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='İndirim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'İndirim oranı',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='heart',
            field=models.ManyToManyField(blank=True, null=True, related_name='heart', to=settings.AUTH_USER_MODEL),
        ),
    ]
