# Generated by Django 3.1.4 on 2021-03-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0040_product_indirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='indirim',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='Main.i̇ndirim'),
        ),
    ]
