# Generated by Django 3.1.4 on 2021-03-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0042_auto_20210307_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='indirim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.i̇ndirim'),
        ),
    ]
