# Generated by Django 3.1.4 on 2021-03-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0048_remove_product_reviewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='İndirim',
        ),
    ]
