# Generated by Django 3.1.4 on 2021-03-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0049_delete_i̇ndirim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indirim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'İndirim oranı',
            },
        ),
    ]
