# Generated by Django 3.1.4 on 2021-03-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0050_indirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirim',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
