# Generated by Django 3.1.4 on 2021-03-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0051_auto_20210310_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirim',
            name='title',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
