# Generated by Django 3.1.4 on 2021-03-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0055_lastreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-reviewed'], 'verbose_name_plural': 'Ürünler'},
        ),
    ]
