# Generated by Django 3.1.4 on 2021-03-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0057_auto_20210313_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='ürün son baktıgım zaman ')),
                ('review', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
            ],
            options={
                'verbose_name_plural': 'Ürünü son goruntuleme',
                'ordering': ['-time'],
            },
        ),
    ]
