# Generated by Django 3.1.4 on 2021-03-14 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0059_lastreview_usersee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastreview',
            name='UserSee',
            field=models.ForeignKey(default='muhammett', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
