# Generated by Django 3.1.4 on 2021-03-15 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0060_auto_20210314_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastreview',
            name='UserSee',
        ),
        migrations.AddField(
            model_name='lastreview',
            name='usersee',
            field=models.ManyToManyField(blank=True, related_name='usersee', to=settings.AUTH_USER_MODEL),
        ),
    ]
