# Generated by Django 3.1.4 on 2021-03-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0061_auto_20210315_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
