# Generated by Django 3.1.4 on 2021-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0062_auto_20210316_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Görüntülenme'),
        ),
    ]
