# Generated by Django 3.1.4 on 2021-03-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0064_remove_product_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
