# Generated by Django 3.1.4 on 2021-04-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0067_auto_20210326_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
