# Generated by Django 3.1.4 on 2021-05-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0068_remove_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='advantage',
            new_name='generalTitle',
        ),
    ]
