# Generated by Django 3.1.4 on 2021-05-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0069_auto_20210502_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.brand', verbose_name='Ürünün Markası '),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.category', verbose_name='Ürünün Kategorisi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='Main.Color', verbose_name='Mevcut Renkleri'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(verbose_name='Ürün Detayı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_imgs/', verbose_name='Ürün Fotografları '),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Eski Fiyat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='Main.Size', verbose_name='Mevcut Boyutları'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(verbose_name='Ürün Özellikleri'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='Ürünün Durumu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Ürün İsmi'),
        ),
    ]
