# Generated by Django 3.1.4 on 2021-05-05 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0070_auto_20210502_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chooseColor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seçilenRenk', to='Main.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='chooseSize',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seçilenSize', to='Main.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heart',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Begenen Kullanıcılar'),
        ),
    ]
