# Generated by Django 3.1.4 on 2021-05-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0071_auto_20210506_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='chooseColor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chooseSize',
        ),
    ]
