# Generated by Django 3.1.4 on 2021-05-07 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_auto_20210507_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0072_auto_20210506_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='İçerik *')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='ürün son baktıgım zaman ')),
                ('orderıtem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.orderitem', verbose_name='Ürün ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum yapan kullanıcı')),
            ],
        ),
    ]
