# Generated by Django 3.1.4 on 2021-05-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0073_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='orderıtem',
        ),
    ]
