# Generated by Django 3.1.4 on 2021-05-07 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0074_remove_comment_orderıtem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='Yorum ')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(related_name='Related_comment_dislike', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='Related_comment_like', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentss', to='Main.product', verbose_name='ürün ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum yazarı ')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
