# Generated by Django 3.1.4 on 2021-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0075_auto_20210507_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(max_length=100, verbose_name='Yorum '),
        ),
    ]
