# Generated by Django 3.1.4 on 2021-05-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0076_auto_20210507_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_date',
            new_name='created_date',
        ),
    ]
