# Generated by Django 3.1.4 on 2021-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0077_auto_20210507_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='product_imgs/', verbose_name='Ürün Fotografları '),
        ),
    ]
