# Generated by Django 3.1.4 on 2021-05-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0080_auto_20210508_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='star',
            field=models.FloatField(default='0.0', max_length=6),
        ),
    ]
