# Generated by Django 3.1.4 on 2021-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0082_auto_20210508_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='star',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Star'),
        ),
    ]
