# Generated by Django 3.1.4 on 2021-05-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0083_auto_20210508_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.product', verbose_name='ürün '),
        ),
        migrations.AlterField(
            model_name='comments',
            name='star',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Star'),
        ),
    ]
