# Generated by Django 3.1.4 on 2021-05-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_auto_20210508_1750'),
        ('Main', '0084_auto_20210508_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.order'),
            preserve_default=False,
        ),
    ]
