# Generated by Django 3.1.4 on 2021-05-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0085_comments_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='orderitem',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
