# Generated by Django 3.1.4 on 2021-05-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_auto_20210508_1750'),
        ('Main', '0086_comments_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='orderitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.orderitem'),
        ),
    ]
