# Generated by Django 3.1.4 on 2021-05-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0088_auto_20210517_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
